qiboteam/qibocal

src/qibocal/cli/builders.py

Closes #114.
As noted by @aorgazf, when running `qq` the platform was connecting twice to the instruments.
The double connection was caused by:
- `set_backend` which for qibolab performs also the connection with the instruments
- allocating a platform with the `updated_runcard`, i.e. the platform runcard which is continuosly updated when we run multiple routines.
In this PR I solved this issue by calling `set_backend` once with the `updated_runcard` directly.
Let me know what you think.

Fix double connection issue

---

.github/workflows/tests.yml

This PR enables tests for all OS.
With the current tests, which need to be extended, qibocal is working with all OS using python >= 3.8.
Many thanks to @Edoardo-Pedicillo for spending a lot of time trying to implement the new workflow.
Checklist:

Enable workflow for multiple OS

---

src/qibocal/calibrations/characterization/allXY.py
src/qibocal/calibrations/characterization/calibrate_qubit_states.py
src/qibocal/calibrations/characterization/flipping.py
src/qibocal/calibrations/characterization/qubit_spectroscopy.py
src/qibocal/calibrations/characterization/rabi_oscillations.py
src/qibocal/calibrations/characterization/ramsey.py
src/qibocal/calibrations/characterization/resonator_spectroscopy.py
src/qibocal/calibrations/characterization/t1.py
src/qibocal/cli/builders.py
src/qibocal/data.py
src/qibocal/plots/heatmaps.py
src/qibocal/plots/scatters.py
src/qibocal/tests/test_data.py
src/qibocal/web/app.py

Hi, In this PR I add a `set()` method to Dataset so that the entire dataframe can be loaded at once from a dictionary, instead of row by row.
I believe this feature had long back been requested by @maxhant .
Row by row is very time consuming, it takes ~5min for adding 1024 rows in a calibrate_qubit_states_binning routine.
example of use:
```python
exc_sequence = PulseSequence()
RX_pulse = platform.create_RX_pulse(qubit, start=0)
ro_pulse = platform.create_qubit_readout_pulse(qubit, start=RX_pulse.duration)
exc_sequence.add(RX_pulse)
exc_sequence.add(ro_pulse)
data_exc = Dataset(name=f"data_exc_q{qubit}", quantities={"iteration": "dimensionless"})
msr, phase, i, q = platform.execute_pulse_sequence(exc_sequence, nshots)['binned_integrated'][ro_pulse.serial]
iq_exc = i + 1j * q
results = { …
```

add Dataset set()

---

.github/workflows/tests.yml
pyproject.toml

As already stated in #130 with this PR we add the possibility to test the documentation examples directly in the workflow using the `doctest` ext available in sphinx. This is exactly the same approach that we use in Qibo.
Checklist:

Testing documentation examples in workflow

---

pyproject.toml
runcards/actions_qq_1q.yml
runcards/actions_qq_5q.yml
src/qibocal/__init__.py
src/qibocal/calibrations/__init__.py
src/qibocal/calibrations/characterization/allXY.py
src/qibocal/calibrations/characterization/qubit_spectroscopy.py
src/qibocal/calibrations/characterization/rabi_oscillations.py
src/qibocal/calibrations/characterization/ramsey.py
src/qibocal/calibrations/characterization/resonator_spectroscopy.py
src/qibocal/calibrations/characterization/spin_echos.py
src/qibocal/cli/__init__.py
src/qibocal/cli/_base.py
src/qibocal/cli/builders.py
src/qibocal/data.py
src/qibocal/fitting/methods.py
src/qibocal/plots/heatmaps.py
src/qibocal/plots/scatters.py
src/qibocal/plots/utils.py
src/qibocal/web/app.py
src/qibocal/web/server.py
src/qibocal/web/templates/template.html

This PR implements qq-compare command in qibocal. The command will check if the folders are comparable between them, so the folders have contain data obtained from the same type of actions using qibocal module.
The use of the command is the following:
1. Execute qq-compare folder_1 folder_2 folder_N (where the arguments are the folders to be compared)
2. Comparision results are stores under "qq-compare" folder located in the users folder
3. Previous comparisons are moved and stored in "qq-compare_{date_time}" folders
4. Open qq-live and click "qq-compare" folder to see the results
All the data regarding same qubits are compare under the same plot. The legends are automatically named with the nomenclature "qm/rn" that should be interpreted as the execution N over qubit M of the given …

qq-compare

---

poetry.lock
pyproject.toml

Closes #142.
This PR fixes the latest installation problems with windows.
Windows was complaining about some symbolic links which are in Qibo.
This issue seems to appear only if in  the `pyproject.toml` we install the latest main of Qibo, instead if we install the latest release of Qibo this issue is no longer present. I think that there is nothing wrong with the latest main of Qibo, probably poetry has some issues when installing "from source" projects that have symbolic links.
The fix proposed in this PR consists in changing the Qibo dependency from the latest main to the latest release, which now is the `0.1.9`.
If the user needs some features which are in the latest main you can also always overwrite the qibo installation in your local environment.
@aorgazf when you have time could …

Fixing windows installation

---

poetry.lock
pyproject.toml

Closes #177 by removing `pre-commit` and `black` from dev deps.
Currently tests are failing because there is an issue with the latest release of  [black](https://github.com/psf/black/issues/3312) on MacOS. 
After talking to @AleCandido we agreed that actually both `black` and `pre-commit` are not needed inside `pyproject.toml`. In fact  `pre-commit` is not needed inside the environment given that the user could commit outside the environment generated by poetry. The same thing is true for `black` given that we are using it only with `pre-commit`.
@scarrazza let me know if you agree.
Checklist:

Fixing tests failing on MacOS

---

runcards/actions_qq_1q.yml
src/qibocal/cli/_base.py
src/qibocal/cli/builders.py

This PR closes #181.
Now it will be possible to specify the platform runcard path in the qq runcard:
```yaml
platform: tii1q_b1
runcard: <path_to_runcard>
qubits: [0]
format: csv
actions:
resonator_spectroscopy:
lowres_width: 5_000_000
lowres_step: 2_000_000
highres_width: 1_500_000
highres_step: 200_000
precision_width: 1_500_000
precision_step: 100_000
software_averages: 2
points: 5
```
`qq` will correctly modify the parameters of the platform runcard provided (I've performed a quick test using the `tii1q_b1` platform using qiboteam/qibolab#255).
We will need to update the documentation. I prefer to do this directly in #121.
Checklist:

Add platform runcard in qq runcard

---

doc/source/conf.py
doc/source/index.rst

In this PR:
- the text font is changed into "Ubuntu";
- the software's version is shown in the side-bar now.

New docs font and version display

---

src/qibocal/calibrations/characterization/qubit_spectroscopy.py
src/qibocal/calibrations/characterization/resonator_spectroscopy.py

Hi,
This PR modifies the names of the qubit biassing ports (from `qf_port` to `qb_port`), so that it works with the minor refactor introduced in qibolab PR#242 Adding the offsets to platforms.
As you may see it only affects the flux spectroscopies.
Checklist:

Refactor qubit biassing port

---

src/qibocal/calibrations/characterization/rabi.py

Hi, 
This PR fixes a bug in the creation of the pulse sequences in some Rabi experiments that was introduced in PR #155.
Thanks @maxhant 
Checklist:

Fix pulse sequence creation in Rabi routines

---

runcards/actions_qq_1q.yml
src/qibocal/calibrations/characterization/qubit_spectroscopy.py
src/qibocal/cli/builders.py

Fixes the behavior of the method `update_platform_runcard` of the `ActionBuilder` that was broken after merging PR #155. After executing all the calibration routines the user will find in the output folder a file `new_platform.yml` with an updated platform runcard. All the parameters in the runcard are updated sequentially.
I've fixed in a typo in the routine `qubit_spectroscopy`.
Checklist:

Fix `update_platform_runcard` method

---

poetry.lock

I've updated the poetry lock file which now supports the latest main available in Qibo.
Checklist:

Update Qibo version in `poetry.lock`

---

src/qibocal/web/report.py

The report (index.html) is not properly rendered after a run is finished. This PR should fix this issue.
Checklist:

Fix bug with report not appearing

---

src/qibocal/calibrations/characterization/allXY.py
src/qibocal/plots/allXY.py

After merging #189 I changed the allXY routines because I thought that in the y axis we were supposed to plot the probability of the ground state (I got confused by the label in the plot). This PR fixes this issue.
Moreover, I changed the y label of the plot to "Expectation value of Z" to avoid future misunderstandings.
Checklist:

Fix allXY plot label and plot

---

src/qibocal/plots/ramsey.py

Fix a plotting bug probably due to some change. Here is the error message:
```
raceback (most recent call last):
File "/home/users/maxime.hantute/.conda/envs/test/bin/qq", line 6, in <module>
sys.exit(command())
File "/home/users/maxime.hantute/.conda/envs/test/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/users/maxime.hantute/.conda/envs/test/lib/python3.9/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/home/users/maxime.hantute/.conda/envs/test/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/users/maxime.hantute/.conda/envs/test/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, …
```

Fix ramsey plotting bug

---

poetry.lock
pyproject.toml

This actually solves compatibility with Poetry modern installer, and so the vanilla 1.4.1 version (without further configurations).

Update Furo to hash-safe version

---

src/qibocal/calibrations/characterization/resonator_spectroscopy.py

This PR fixes a bug in the `dispersive_shift()` routine, that manifested when performing multiplexed scans.
With the bug, the would wrongly save the frequency of the last qubit for all qubits.
Checklist:

replace ro_pulses[qubit].frequency with ro_pulse.frequency

---

src/qibocal/calibrations/characterization/ro_optimization.py
src/qibocal/fitting/methods.py
src/qibocal/plots/ro_optimization.py

Readout optimization for the TWPA parameters. 
It is tested with a merged of `qibolab` : 
1. https://github.com/qiboteam/qibolab/pull/386 
2. https://github.com/qiboteam/qibolab/tree/alvaro/qblox9_sweepers
But it should work with any sweeper branch as soon as 1. is merged in Qibolab. 
It can be tested:
```yml
platform: qblox
runcard: /home/users/maxime.hantute/qibolab/src/qibolab/runcards/qw5q_gold_qblox.yml
qubits: [0,1,2,3,4]
format: csv
actions:
ro_frequency:
frequency_width: 2.e+6
frequency_step: .1e+6
nshots: 2000
ro_amplitude:
amplitude_factor_min: 0.8
amplitude_factor_max: 1.1
amplitude_factor_step: 0.1
nshots: 2000
twpa_frequency:
frequency_width: 50.e+6
frequency_step: 10.e+6
nshots: 2000
twpa_power:
power_width: 1
power_step: 0.1
nshots: 2000
```
Checklist:

Readout optimization for TWPA

---

src/qibocal/fitting/methods.py

The PR fixes the bug introduced in the calculation of the rotation angle and threshold of the `calibrate_qubit_states_fit` function.
With this fix, AllXYs work again.
Checklist:

Fix Classification Parameters closes #305

---

src/qibocal/fitting/methods.py
src/qibocal/fitting/utils.py
tests/test_fitting_methods.py

This PR implements and benchmarks a new function to evaluate the cumulative distribution.
To compare the old method (`method1`) with the new one (`method2`), you can use the following code
```python
import time
import numpy as np
import matplotlib.pyplot as plt
REPETITIONS = 100
def cum_method1(real_values_combined, real_values_state0):
return  [
sum(map(lambda x: x.real >= real_value, real_values_state0))
for real_value in real_values_combined
]
def cum_method2(input_data, points):
input_data = np.sort(input_data)
points = np.sort(points)
prob = []
app = 0
for val in input_data:
app += np.max(np.searchsorted(points[app::], val), 0)
prob.append(app)
return np.array(prob)
def time_compare(method, input1, input2):
start = time.time()
for _ in range(REPETITIONS):
cum =  method(input1, …
```

Cumulative

---

doc/source/getting-started/niGSC/niGSC_and_standardrb.rst

This PR updates the examples for Standard Randomized Benchmarking in [documentation](https://qibo.science/qibocal/stable/getting-started/niGSC/niGSC_and_standardrb.html#non-interactive-gate-set-characterization).
Checklist:

Update RB examples in documentation

---

src/qibocal/protocols/characterization/allxy/allxy.py

Fix indentation error in allXY aquisition routine
Checklist:

fixed allXY indentation

---

src/qibocal/protocols/characterization/ramsey.py

Simplify the Ramsey code as suggested by @igres26 following #337.
This PR will not fix the bug for qblox as it is related to a problem with the relative phase.
I tried to test it this morning with qblox but I think that something is not working.
@Jacfomg could be please rerun quickly the sanity check that we ran yesterday using iqm?
Checklist:

Simplify Ramsey code

---

src/qibocal/protocols/characterization/__init__.py
src/qibocal/protocols/characterization/qubit_spectroscopy.py
src/qibocal/protocols/characterization/resonator_spectroscopy.py
src/qibocal/protocols/characterization/resonator_spectroscopy_attenuation.py
src/qibocal/protocols/characterization/utils.py
tests/runcards/single_routines.yml
tests/runcards/test_autocalibration.yml
tests/test_operations.py

Closes #360.
I've added a different routine to set the attenuation in the resonator spectroscopy called `ResonatorSpectroscopyAttenuation`. This is just a quick fix.
Checklist:

Detach attenuation from resonator spectroscopy

---

src/qibocal/calibrations/niGSC/basics/noisemodels.py
tests/test_niGSC_noisemodels.py
tests/test_niGSC_standardrb.py

Fix niGSC tests for new qibo version

---

tests/runcards/single_routines.yml
tests/test_protocols.py

This PR improves the following [test](https://github.com/qiboteam/qibocal/blob/name_tests/tests/test_protocols.py) by showing the id of the protocols which is currently executed. Before the id of the test was quite generic `runcard1`, `runcard2` and so on.
Checklist:

Show protocol id in tests

---

src/qibocal/protocols/characterization/dispersive_shift.py

Closes #430.
I've also renamed `Frequency Shift` to `Chi` by dividing the shift by two (hopefully it is correct).
Checklist:

Fix dispersive shift updated frequency

---

src/qibocal/auto/execute.py
src/qibocal/cli/_base.py
src/qibocal/cli/builders.py
src/qibocal/protocols/characterization/ramsey.py
src/qibocal/protocols/characterization/resonator_spectroscopy.py
src/qibocal/protocols/characterization/utils.py
tests/test_auto.py
tests/test_task_options.py

As title says, closes #436
Checklist:

Dump report after each protocol

---

.github/pull_request_template.md

I would like to introduce this new PR template to force people to specify which branches should be used by the reviewers to test the PRs.
Checklist:

add branches in PR template

---

poetry.lock
pyproject.toml

Currently the lock file cannot be updated:
```sh
Because no versions of tensorflow match >2.12.0,<2.12.1 || >2.12.1,<2.13.0 || >2.13.0,<3.0.0
and tensorflow (2.13.0) depends on numpy (>=1.22,<=1.24.3), tensorflow (>2.12.0,<2.12.1 || >2.12.1,<3.0.0) requires numpy (>=1.22,<=1.24.3).
And because tensorflow (2.12.1) depends on numpy (>=1.22,<=1.24.3)
and tensorflow (2.12.0) depends on numpy (>=1.22,<1.24), tensorflow (>=2.12.0,<3.0.0) requires numpy (>=1.22,<=1.24.3).
So, because qibocal depends on both numpy (^1.25.0) and tensorflow (^2.12.0), version solving failed.
```
this PR fixes this  issue by downgrading numpy from `1.25` to `1.24` .
Checklist:

Downgrade numpy dep to fix tf issue

---

src/qibocal/protocols/characterization/__init__.py
src/qibocal/protocols/characterization/readout_characterization.py
src/qibocal/protocols/characterization/resonator_spectroscopy.py
tests/runcards/protocols.yml

As per https://arxiv.org/abs/2106.06173. Calculate Fidelity and QND-ness of our readout.
Works with https://github.com/qiboteam/qibolab/pull/517
Checklist:

Readout characterization

---

src/qibocal/auto/execute.py
src/qibocal/auto/operation.py
src/qibocal/auto/task.py
src/qibocal/cli/builders.py
src/qibocal/config.py

This PR adds some logs in order to show which protocol is being executed.
The timing of both the acquisition and the fitting are shown for each protocol.
Here is an example
Checklist:

Adding logs

---

src/qibocal/protocols/characterization/dispersive_shift.py

Basically, the dispersive shift didn't work for qubitId that weren't number, this should solve it
Checklist:

Fix dispersive shift (qubit as str)

---

src/qibocal/protocols/characterization/rabi/amplitude.py
src/qibocal/protocols/characterization/rabi/length.py
src/qibocal/protocols/characterization/ramsey.py

Closes #475.
After performing the FFT I added the [`find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) primitive from `scipy`.
In the case where not oscillations are observed the initial guess for the oscillations is 0.5.
I tried it on hardware and it seems to work as expected.
Checklist:

Fix problems with Rabi fitting

---

doc/source/getting-started/example.rst

Indent typo in the example runcard doc.
Checklist:

Indent typo in the runcard

---

doc/source/getting-started/interface.rst

I added instructions explaining how to access the servers with uploaded reports. It is just a copy-paste from `Reame.md`.
Checklist:

Added qq upload instructions to documentation

---

src/qibocal/protocols/characterization/utils.py

There was a typo in how the lorentzian offset guess was computed.
Checklist:

Now excluding differences lower than -1*st.dev.

---

src/qibocal/auto/task.py
src/qibocal/protocols/characterization/__init__.py
src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/spin_echo_msr.py
src/qibocal/protocols/characterization/coherence/t1.py
src/qibocal/protocols/characterization/coherence/t1_msr.py
src/qibocal/protocols/characterization/coherence/t1_sequences.py
src/qibocal/protocols/characterization/coherence/t2.py
src/qibocal/protocols/characterization/coherence/t2_msr.py
src/qibocal/protocols/characterization/coherence/t2_sequences.py
src/qibocal/protocols/characterization/coherence/utils.py
src/qibocal/protocols/characterization/coherence/zeno.py
src/qibocal/protocols/characterization/coherence/zeno_msr.py
src/qibocal/protocols/characterization/ramsey_msr.py
src/qibocal/update.py
tests/runcards/protocols.yml

In this PR I'm planning to add new protocols where the y axes correspond to probabilities and not longer MSR.
In this way we can use again the error given by the binomial distribution.
Protocols to modify:
For the time being I'm keeping the ones with MSR. In the future we can think about removing them and just compute T1, T2, .. after single shot classification.
Checklist:

Adding "coherence"  protocols with probabilities and error bands. 

---

src/qibocal/fitting/classifier/qubit_fit.py
src/qibocal/fitting/classifier/run.py
tests/test_auto.py
tests/test_classifiers.py
tests/test_protocols.py
tests/test_task_options.py

After talking with @stavros11 we realized that now importing qibocal takes longer than usual.
After profiling the import we discover that importing `skops` introduces an overhead of around 2 seconds.
Here is the profiling with skops:
This PR reduces the import time by moving `skops` as a relative import.
Here is the updated profiling:
Checklist:

Reducing import overhead

---

serverscripts/web/index.html

Fixes ordering of report based on date instead of execution start.
The server is already updated.

fixing ordering table

---

src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py

fix chevron for no couplers

---

src/qibocal/auto/operation.py
src/qibocal/auto/task.py
tests/runcards/protocols.yml

Closes #594 
Parameters not explicitly defined in the qibocal runcard are read from qibolab runcards.
Checklist:

Platform default parameters read from qibolab platforms

---

src/qibocal/protocols/characterization/readout_optimization/resonator_amplitude.py
src/qibocal/protocols/characterization/readout_optimization/resonator_frequency.py
src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py
src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_power.py
src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power.py

Fix update in readout optimization protocols

---

src/qibocal/protocols/characterization/readout_mitigation_matrix.py

It closes #615.
I decided to delete `create_annotated_heatmap` since it is [deprecated](https://plotly.com/python/annotated-heatmap/#:~:text=As%20of%20version%205.5.0%20of%20plotly%2C%20the%20recommended%20way%20to%20display%20annotated%20heatmaps%20is%20to%20use%20px.imshow()%20rather%20than%20the%20now%2Ddeprecated%20create_annotated_heatmap%20figure%20factory%20documented%20below%20for%20historical%20reasons.).
The suggested replacement is `imshow` from plotly express, but because of a problem with dash, it is not able to diplay the text on the matrix cells.
Checklist:

fix mitigation matrix

---

src/qibocal/protocols/characterization/readout_characterization.py

plot clouds in readout_characterization

---

doc/source/getting-started/index.rst
doc/source/getting-started/validation.rst
src/qibocal/auto/execute.py
src/qibocal/auto/runcard.py
src/qibocal/auto/status.py
src/qibocal/auto/task.py
src/qibocal/auto/validation.py
src/qibocal/auto/validators.py
src/qibocal/auto/validators/__init__.py
src/qibocal/auto/validators/chi2.py
src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/t1.py
src/qibocal/protocols/characterization/coherence/t2.py
src/qibocal/protocols/characterization/coherence/zeno.py
src/qibocal/protocols/characterization/ramsey.py
tests/runcards/chi_squared.yml
tests/test_protocols.py
tests/test_validators.py

First attempt at introducing a validation in Qibocal through chi2.
Here is a possible runcard:
```yaml
platform: dummy
qubits: [0,1]
actions:
- id: ramsey
priority: 0
operation: ramsey
validator:
scheme: chi2
parameters:
chi2_max_value: 0.1
parameters:
delay_between_pulses_start: 16 # must be a multiple of 4 incl 0
delay_between_pulses_end: 1000
delay_between_pulses_step: 4 # must be a multiple of 4
n_osc: 10
```
For now I am just planning to add the `chi2` attribute in all protocols that implements errors.
Currently I believe that this works for `ramsey`, `rabi amplitude` and `rabi length`.
I tried to make it already quite validation scheme agnostic in case we want to add other validation schemes.
I am still not sure about how to handle the `Broken` status case. For now the easiest …

Implementing validation using Chi squared

---

src/qibocal/protocols/characterization/dispersive_shift.py

Closes #646.
There was a factor 1e9 wrong (possibly forgotten in #627)..
Checklist:

Fix dispersive shift plot

---

src/qibocal/cli/upload.py

Closes #671 (point 2).
Checklist:

Return url when running `qq upload`

---

src/qibocal/protocols/characterization/rabi/utils.py

Closes #656.
I think there was a problem with some simplification in the correction formula for the rabi period estimate.
Checklist:

Hotfix for rabi period estimate

---

src/qibocal/protocols/characterization/classification.py

This PR fixes #676, the issue was that the temperature was evaluated on the dataset with ground and excited points. What it should be done (not sure) is to consider the dataset containing only the ground state and evaluate the temperature with its predictions.
Checklist:

fix temperature

---

src/qibocal/auto/task.py
tests/runcards/protocols.yml
tests/test_protocols.py

Closes #709.
A `platform` folder will now appear under each `protocol` folder in the report.
I've also made tests a bit more robust by checking if certain files/folders are present.
Checklist:

Dump platform iteratively

---

src/qibocal/protocols/characterization/flipping.py
src/qibocal/protocols/characterization/flipping_signal.py

@Edoardo-Pedicillo possible issues on the flipping, can you have a look and confirm them ?
Checklist:

possible issues

---

src/qibocal/protocols/characterization/flipping.py
src/qibocal/protocols/characterization/flipping_signal.py
src/qibocal/protocols/characterization/ramsey.py
tests/runcards/protocols.yml

It adds support for sequence unrolling in flipping and flipping_signal as requested in https://github.com/qiboteam/qibolab_platforms_qrc/pull/119. It has only been tested with dummy.
Checklist:

Add support for sequence unrolling in flipping and flipping_signal

---

src/qibocal/protocols/characterization/__init__.py
src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
tests/runcards/protocols.yml

Closes #724.
I've added the option to unroll sequences when running spin echo which should improve performances.
There was also a typo since the protocol `spin_echo_sequences` was actually implementing `spin_echo_signal` which I fixed.
Checklist:

Adding unrolling to spin echo

---

src/qibocal/auto/runcard.py

Closes #727
The bug was generated by a `cached_property` which is not necessary anymore I believe.
Checklist:

Fixing platform and backend assignment through CLI

---

pyproject.toml
src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/spin_echo_sequence.py
src/qibocal/protocols/characterization/coherence/utils.py

Improved fitting in exponential decays involving probabilities by adding a z_score normalization for data on the x_axis.
Here are some reports with T1, T2 and Spin Echo
http://login.qrccluster.com:9000/ETjYKXbbTM-cxWOuiWYz7Q==
http://login.qrccluster.com:9000/NsZ1y2OrRcy2tA3XbIKmTw==
http://login.qrccluster.com:9000/z8xLdg6NSseFpLQam7O-7g==
Checklist:

Fix fitting with probabilities

---

src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
src/qibocal/protocols/characterization/coherence/t1.py
src/qibocal/protocols/characterization/coherence/t1_sequences.py
src/qibocal/protocols/characterization/coherence/t1_signal.py
src/qibocal/protocols/characterization/coherence/t2.py
src/qibocal/protocols/characterization/coherence/t2_signal.py
src/qibocal/protocols/characterization/coherence/zeno.py
src/qibocal/protocols/characterization/coherence/zeno_signal.py
src/qibocal/protocols/characterization/flipping.py
src/qibocal/protocols/characterization/flipping_signal.py
src/qibocal/protocols/characterization/qubit_spectroscopy.py
src/qibocal/protocols/characterization/rabi/amplitude.py
src/qibocal/protocols/characterization/rabi/amplitude_signal.py
src/qibocal/protocols/characterization/ramsey/ramsey.py
src/qibocal/protocols/characterization/ramsey/ramsey_signal.py
src/qibocal/protocols/characterization/resonator_spectroscopy.py

Fixing issue spotted by @igres26 in https://github.com/qiboteam/qibolab_platforms_qrc/pull/119#issuecomment-1975121779.
The problem was caused by a side effect introduced in #707.
Checklist:

Solve missing plot for protocols involving chi2

---

src/qibocal/protocols/characterization/utils.py

Closes #741.
There was no error in the fit since also the table shows the correct fitted value, the problem was just a factor 10^9 in the plot.
It is possible to test the fit by simply running 
```sh
qq fit <output_folder>
```
and to generate the new report
```sh
qq report <output_folder>
```
Checklist:

Fix bug in lorentzian plot for spectroscopies

---

src/qibocal/auto/operation.py
src/qibocal/protocols/characterization/classification.py

fix: Added json extension to results for singleshot classification

---

src/qibocal/auto/operation.py
src/qibocal/cli/report.py

Closes #743 .
The following implementation does not require a marker file which I think is better.
Checklist:

Adding error message when fitting failed

---

src/qibocal/protocols/characterization/rabi/length.py
src/qibocal/protocols/characterization/rabi/length_signal.py

In #744 I forgot to update the rabi length protocol.
EDIT: Improved fit for rabi length with probabilities.
Checklist:

Hotfix for rabi length following #744

---

doc/source/protocols/resonator_punchout.rst
doc/source/protocols/resonator_spectroscopy.rst
doc/source/tutorials/advanced.rst
doc/source/tutorials/basic.rst
runcards/benchmarks/routines_benchmarks.yml
runcards/benchmarks/scaling_benchmarks.yml
runcards/calibration_tutorial/classification.yaml
runcards/calibration_tutorial/qubit_flux_dependence.yaml
runcards/calibration_tutorial/qubit_spectroscopy.yaml
runcards/calibration_tutorial/rabi.yaml
runcards/calibration_tutorial/ramsey.yaml
runcards/calibration_tutorial/rb.yaml
runcards/calibration_tutorial/readout_characterization.yaml
runcards/calibration_tutorial/resonator_punchout.yaml
runcards/calibration_tutorial/resonator_spectroscopy_high.yaml
runcards/calibration_tutorial/resonator_spectroscopy_low.yaml
runcards/calibration_tutorial/t1.yaml
runcards/monitor.yml

Removing `priority`, `next` and `main` from some runcards and documentation.
Checklist:

Remove outdated keys after DAG remove

---

runcards/actions_qq.yml
src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/t1.py
src/qibocal/protocols/characterization/coherence/t2.py
src/qibocal/protocols/characterization/coherence/utils.py
src/qibocal/protocols/characterization/coherence/zeno.py
src/qibocal/protocols/characterization/qubit_spectroscopy_ef.py
src/qibocal/protocols/characterization/rabi/amplitude.py

Fixing rabi issue when fitting fails 

---

src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py

Now when running CHSH the mitigation matrix will be stored in a `mitgation_matrix.npz` file.
It should be useful for debugging but also in order to generate the CHSH value after performing the acquisition (`qq acquire`) with `qq fit`. 
For the future it might be interesting to have this behave like kernels if we want to support readout mitigation (of course also qibolab will need to be updated to support this feature).
Checklist:

Store mitigation matrix when running  CHSH

---

src/qibocal/protocols/characterization/randomized_benchmarking/circuit_tools.py
src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
tests/test_randomized_benchmarking.py

>[!CAUTION]
> It requieres https://github.com/qiboteam/qibolab/pull/864 to fix RB completely.
This will save the random indexes in the data.json from the reports. And fix the RB random number generation.
Checklist:

Save random_indexes for the RB

---

src/qibocal/cli/autocalibration.py

Currently in the report start time and end time were the same due to a small bug.
This PR fixes the issue.
Checklist:

Show end time correctly in HTML report

---

src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py

Closes #798.
I removed the `resonator_type` check since it is not needed given that we will use just 2D resonators with flux tunable qubits. If someone can confirm this I can also drop the `resonator_type` from the data structure.
Checklist:

Hotfix for `extract_feature` function

---

src/qibocal/protocols/characterization/coherence/spin_echo.py
src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
src/qibocal/protocols/characterization/dispersive_shift.py
src/qibocal/protocols/characterization/dispersive_shift_qutrit.py
src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py
src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
src/qibocal/protocols/characterization/qubit_spectroscopy.py
src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
src/qibocal/protocols/characterization/resonator_punchout.py
src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
src/qibocal/protocols/characterization/resonator_spectroscopy.py

This PR closes #762 
Checklist:

fix frequency range type

---

src/qibocal/protocols/characterization/readout_characterization.py
tests/runcards/protocols.yml

The fidelity and QND do not seem affected when neglecting the resonator delation time as we are not applying qubit pulses during the measurements. However, there is some anomalous shift on the iq plane that goes away if you wait the resonator depletion time.
Checklist:

Delay on readout characterization

---

src/qibocal/protocols/characterization/two_qubit_interaction/chsh/utils.py

Handling `ZeroDivisionError`

---

src/qibocal/protocols/randomized_benchmarking/utils.py

Proper import for defaultdict
Checklist:

Proper import for defaultdict

---

src/qibocal/protocols/signal_experiments/time_of_flight_readout.py

Remove unused pulse in time of flight experiment
Checklist:

Remove unused pulse in tof

---

src/qibocal/protocols/two_qubit_interaction/cz_virtualz.py

Proper name for fit functions

---

src/qibocal/protocols/rabi/utils.py

Closes #879.
I guess that the "problem" arises from the fact that in rabi length we expect to see oscillations given by detuning (potential at least) spanning along a large duration. While for rabi amplitude the length is usually kept small -> we do not fit oscillation and we don't have the same problem.
I'm not sure that I like the asymmetry, but it doesn't probably matter
Checklist:

Fix Rabi length signal fit

---

src/qibocal/protocols/dispersive_shift.py

Closes #887, but does not take care at all of #890.
How could we use `params.execution_parameters` and also pass standard values?
Checklist:

unify execution pars for dispersive shift

---

.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

The main benefit of `v1` is the name itself, since I'd like to finally move towards workflows versioning.
However, there are already two improvements:
1. the cache is not present any longer, that should solve https://github.com/qiboteam/workflows/issues/64
2. I now enabled the modern installer (not sure why it was disabled, or still disabled) which may solve some installation problems experienced recently (which signature was something like `  IncompleteRead(* bytes read, * more expected)`, e.g. [this run](https://github.com/qiboteam/qibocal/actions/runs/9806408242/job/27078063843#step:7:38))

Switch reusable workflows to v1

---

src/qibocal/protocols/readout_optimization/twpa_calibration/frequency_SNR.py
src/qibocal/protocols/readout_optimization/twpa_calibration/frequency_power.py
src/qibocal/protocols/readout_optimization/twpa_calibration/power_SNR.py

Some issues I realized while trying to use these routines:
1. `frequency_power` was giving some `KeyError`s with `qubit`s missing from the `initial_twpa_freq` and `initial_twpa_power` dictionaries. I believe these are because the execution part of the routine is nested in the loop that initializates these dictionaries, while I think it should be a separate loop.
2. It seems that `relaxation_time` is ignored for both SNR routines as it is not passed in the `resonator_spectroscopy` call. This ends up using the default `relaxation_time` from the platform runcard, which is usually much higher than what we need for spectroscopy, thus making execution slower.
Checklist:

Small fixes for TWPA calibration routines

---

src/qibocal/protocols/drag.py
src/qibocal/protocols/flipping.py
src/qibocal/protocols/flipping_signal.py
src/qibocal/protocols/rabi/amplitude.py
src/qibocal/protocols/rabi/amplitude_frequency.py
src/qibocal/protocols/rabi/amplitude_frequency_signal.py
src/qibocal/protocols/rabi/amplitude_signal.py
src/qibocal/protocols/rabi/length.py
src/qibocal/protocols/rabi/length_frequency.py
src/qibocal/protocols/rabi/length_frequency_signal.py
src/qibocal/protocols/rabi/length_signal.py
src/qibocal/protocols/rabi/utils.py
src/qibocal/protocols/ramsey/ramsey.py
src/qibocal/protocols/ramsey/ramsey_signal.py
src/qibocal/protocols/ramsey/utils.py
src/qibocal/protocols/two_qubit_interaction/utils.py
src/qibocal/protocols/utils.py
tests/runcards/protocols.yml
tests/test_executor.py
tests/test_fft.py
tests/test_rabi.py

Closes https://github.com/qiboteam/qibocal/issues/897.
Checklist:

Fixing fft guess 

---

src/qibocal/protocols/rabi/amplitude_signal.py

I guess this was just an oversight, because of the asymmetry with the length signal.

Add missing default value

---

poetry.lock
src/qibocal/protocols/classification.py

When plotting from file using `qq report` the fit was never appearing for single shot classification.
This PR fixes the issue.
@Edoardo-Pedicillo for the time being this is mostly a patch, if you have a better solution let me know
Checklist:

Fix classifiers plot

---

src/qibocal/protocols/drag.py

I missed a `HZ_TO_GHZ` conversion in #927.
Here is an example: http://login.qrccluster.com:9000/2_PXMY2xQBSV1w9CC1yezQ==
Checklist:

Hotfix for drag protocol

---

src/qibocal/__init__.py
tests/test_executor.py

Initially setting it to dummy, to avoid loading attempts from other platforms, through undesired env vars
- ~~convert one of the two example scripts to `qibocal.routines`~~ done in #949

Fix default executor platform

---

src/qibocal/protocols/coherence/spin_echo.py
src/qibocal/protocols/rabi/amplitude.py
src/qibocal/protocols/rabi/amplitude_signal.py
src/qibocal/protocols/rabi/utils.py
src/qibocal/protocols/two_qubit_interaction/chevron/chevron.py
src/qibocal/protocols/two_qubit_interaction/utils.py

Closes #957 and https://github.com/qiboteam/qibocal/issues/956#issuecomment-2262771447
For Rabis I just made the bounds a bit larger and change some initial conditions.
For Chevron I did a small refactor of the fit in order to take no longer the FFT but the row where there are more oscillations.
I've tested both and they seems to work as expected.
Checklist:

Rabi and chevron fixes

---

runcards/rx_calibration.py
runcards/single_shot.py
src/qibocal/auto/execute.py
tests/test_executor.py

This is more or less complete as it is.
I will test, but it is already doing little to nothing.
Since this was originally an idea by @andrea-pasquale, I'd say it is ready for *your* review in the first place, and I'd like to collect your feedback.

Executor context manager

---

src/qibocal/protocols/flux_dependence/qubit_flux_dependence.py
src/qibocal/protocols/flux_dependence/utils.py

The error comes from the fact there was a redundant factor pi which is already included in 
https://github.com/qiboteam/qibocal/blob/78d4938552e46b678e4b6f10acc2bea64e039cc1/src/qibocal/protocols/flux_dependence/utils.py#L220-L221
Checklist:

Hotfix for sweetspot calculation

---

src/qibocal/protocols/state_tomography.py

Small improvements for single qubit tomography including:
- comparison is now performed with the target density matrix without shots noise
- circuit is stored in qasm
Checklist:

Improvements in single qubit state tomography

---

doc/source/protocols/ramsey/ramsey.rst
src/qibocal/protocols/ramsey/ramsey.py
src/qibocal/protocols/ramsey/ramsey_signal.py
src/qibocal/protocols/ramsey/utils.py

The drive frequency is now updated only when a detuning is provided, which is one of the assumption of the fit. When detuning is 0 we update T2 since we expect it to be more reliable.
Now Ramsey can be used to monitor T2 in a more stable way given that the fit will include both oscillations and an exponential decay.
Checklist:

Fix ramsey update

---

src/qibocal/protocols/rabi/amplitude_frequency.py
src/qibocal/protocols/rabi/amplitude_frequency_signal.py
src/qibocal/protocols/rabi/length_frequency.py
src/qibocal/protocols/rabi/length_frequency_signal.py

Closes #991.
I would like to add a test to verify that the code works properly.
I don't know if this is feasible unless we use some regressions.
Checklist:

Fix bug in rabi 2D fit

---

src/qibocal/protocols/flux_dependence/resonator_crosstalk.py
src/qibocal/protocols/flux_dependence/resonator_flux_dependence.py

- coupling unit conversion
- update fix
http://login.qrccluster.com:9000/I83qd7qkTzOTWnvl_VOBKA==/
Checklist:

Minor fix in resonator flux dependence

---

src/qibocal/auto/task.py

This PR is a patch to solve the serialization of Circuit parameters, like in state tomographies (this happens with the scripts). Maybe a better solution would be to define a dump method specific for each parameter class and call it directly in the action dump method.
Checklist:

Circuit serialization as parameters of the tomography

---

README.md
doc/dev/README.md

Protocols list

---

src/qibocal/protocols/two_qubit_interaction/virtual_z_phases_signal.py

In VZ signal experiment sweep phase as absolute, instead of relative to match the non-signal experiment

---

src/qibocal/protocols/couplers/coupler_chevron.py
src/qibocal/protocols/two_qubit_interaction/chevron/chevron.py
tests/runcards/protocols_couplers.yml

- Run acquisition in DISCRIMINATION mode. This makes it easier to interpret the results of the experiment.
- Sweeps the qubit flux pulse duration as well (in tandem with coupler flux pulse duration).

coupler_chevron improvements

---

src/qibocal/protocols/two_qubit_state_tomography.py

Fixes #1032. I have not tested how this affect results from hardware, but it is quite clear that the fix is needed (otherwise the real and imaginary part are not compatible).
I also updated the docstring of the `_fit` method with more clear descriptions of the process steps, instead of the wikipedia link, which I think was more confusing than helping.

Fix 2q tomography

---

src/qibocal/protocols/two_qubit_interaction/optimize.py
src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py
src/qibocal/protocols/two_qubit_interaction/virtual_z_phases_signal.py

Just removing the virtual phases set in the creation of the CZ gate from the routine. 
Checklist:

Removing virtual phase from CZ routine, as it might interfere with the calibration of the virtual phase

---

src/qibocal/protocols/readout_mitigation_matrix.py
src/qibocal/protocols/two_qubit_interaction/chsh/circuits.py

In principle, https://github.com/qiboteam/qibolab/pull/1096 should address the issue of `chsh_circuits` producing different results compared to `chsh_pulses`*, however in the definitions of experiments it is still good to explicitly have qubits measured at once/in one circuit moment.
\* The discrepancy is clearly visible in this two reports: [chsh_pulses](http://login.qrccluster.com:9000/WPLE0h22TGSJb9ynR70azg==/), [chsh_circuits](http://login.qrccluster.com:9000/6p6EaKgYRlyd1UGJXaxUwA==/)

in chsh_circuits, measure qubits simultaneously

---

src/qibocal/protocols/two_qubit_interaction/chsh/circuits.py
src/qibocal/protocols/two_qubit_interaction/chsh/protocol.py

http://login.qrccluster.com:9000/5cMEhOV6QoySyihT744y2w==/
Checklist:

Increase the compatibility between transpiler and chsh

---

src/qibocal/auto/operation.py
src/qibocal/protocols/readout_mitigation_matrix.py
src/qibocal/protocols/two_qubit_interaction/chsh/protocol.py
src/qibocal/protocols/two_qubit_interaction/mermin/protocol.py
tests/runcards/protocols.yml

- Remove pulse option
- use proper data attribute
- simplify post-processing
- fix bug (matrix flipping)
- (small fixes in mermin)
- propagate in CHSH
http://login.qrccluster.com:9000/ots5pm92QcWJRS5-lJx4Fg==/
Checklist:

Refactor readout mitigation matrix routine

---

poetry.lock
pyproject.toml
src/qibocal/protocols/randomized_benchmarking/utils.py
src/qibocal/protocols/readout_mitigation_matrix.py
src/qibocal/protocols/state_tomography.py
src/qibocal/protocols/two_qubit_state_tomography.py
tests/test_task_options.py
tests/test_transpile.py

change from GlobalBackends() call to get_backend() call for compatibility with qibo v0.2.13
Checklist:

Fix backend call

---

src/qibocal/protocols/two_qubit_interaction/chsh/protocol.py

Ports the fix of https://github.com/qiboteam/qibocal/blob/293e2a9105568026bb2ee2a94062b381aa8c34bc/src/qibocal/protocols/two_qubit_interaction/mermin/protocol.py#L99
in CHSH, because the platform is disconnected after the error mitigation routine (due to circuit execution).

`platform.connect()` when running CHSH with error mitigation

---

doc/source/protocols/flux/single.rst
src/qibocal/protocols/flux_dependence/qubit_flux_dependence.py
src/qibocal/protocols/flux_dependence/resonator_crosstalk.py
src/qibocal/protocols/flux_dependence/resonator_flux_dependence.py
src/qibocal/protocols/flux_dependence/utils.py

This PR solves #1067 and improves the documentation for qubit flux dependency.
By re-executing the fit of the report in the issue, this is the final result http://login.qrccluster.com:9000/nR6UbuqNQB2FTe7hRsI2Ww==/
EDIT: updated version with the sweetspot plot http://login.qrccluster.com:9000/E8Q42n_PRhyPS3WZbCLDVg==/

Evaluate the sweetspot closest to the center of bias interval

---

src/qibocal/protocols/two_qubit_interaction/optimize.py
src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py
src/qibocal/protocols/two_qubit_interaction/virtual_z_phases_signal.py
tests/runcards/protocols.yml

- Remove parameters `flux_pulse_amplitude` and `flux_pulse_duration` from the experiment `correct_virtual_z_phases`. I think they are not usefull - nobody is going to manually try out various combinations of these parameters to find a good one. There is the `optimize_two_qubit_gate` for this type of task.
- BTW, `flux_pulse_duration` was not even used, it was ignored and always the flux pulse duration from platform was used.
- Get rid of the `amplitude` argument of the `create_sequence` function (as a consequence of the change in the above point). Rename the `duration` argument to `flux_pulse_max_duration` - this is needed for the optimize routine to make sure there is enough room for the duration sweep, and the flux pulse does not overlap with readout (this is different from `dt`, which …

conditional and virtual phase experiment improvements

---

src/qibocal/protocols/qubit_spectroscopy_ef.py
src/qibocal/protocols/qutrit_classification.py

In this PR I'm adjusting a few issues which I found in some qutrits related protocols.
- Adjusting the amplitude and the duration of the drive12 pulse in `qubit_spectroscopy_ef`
- Sweeping over the correct channel in the same protocol
- Putting `None` as fit in the plotting method for the qubit spectroscopy
Here is a report with the corrected protocols http://login.qrccluster.com:9000/IpYZZKreQ3C4fObr4W68Mg==/

Small fixes for qutrits protocols

---

src/qibocal/protocols/readout_optimization/resonator_frequency.py

We fixed the incorrect handling of the dimensions in the data processing of the readout frequency optimization experiment.
Before fix: http://login.qrccluster.com:9000/fm9khE2vSOe4PD3Az8uywQ==
After fix: http://login.qrccluster.com:9000/viE48NXFS6ySplY9syja9Q==

fix incorrect handeling of dimensions in data  processing

---

src/qibocal/auto/serialize.py

Currently, when the data key is a tuple (for instance when a QubitPairID is used as key in the stored data) the Jason keys are stored as "[['q1','q2'], 'some_key', 'some_other_key']". This then gets converted into a tuple as (['q1','q2'], 'some_key', ...) . This immediatly generates an error since the first item, a list, is unhashable and therefore cannot be used as a key in the dictionary. Instead, any nested list in the keys need to also be converted to a tuple.

Update in serialize.load method. 

---

src/qibocal/auto/transpile.py

This PR generalizes the transpilation pipeline in qibocal to support also the case where we have a platform with just one qubit, which was necessary to run circuit-based protocols with the emulator.

Fix transpilation to work also with one qubit

---

src/qibocal/protocols/coherence/t1.py
src/qibocal/protocols/coherence/utils.py
src/qibocal/protocols/flux_gate.py
src/qibocal/protocols/rabi/utils.py
src/qibocal/protocols/ramsey/ramsey.py
src/qibocal/protocols/ramsey/ramsey_zz.py

This PR addresses an error in the duration sweeper of the flux_gate protocol.
I've also decided to add error bars to the plot and I've removed some duplicate variables `COLORBAND` and `COLORBANDLINE`.
Here is the updated protocol: http://login.qrccluster.com:9000/_YxzqVClTsSys8iO4ap53w==/

Fix flux_gate protocol sweeper

---

platforms/qubit/parameters.json
platforms/qubit/platform.py
platforms/qutrit/parameters.json
platforms/qutrit/platform.py

After merging https://github.com/qiboteam/qibolab/pull/1186, the platforms here needed to be updated.

Update emulator platforms

---

src/qibocal/auto/history.py
src/qibocal/auto/operation.py
src/qibocal/auto/output.py
src/qibocal/auto/runcard.py
src/qibocal/auto/task.py
src/qibocal/calibration/calibration.py
src/qibocal/cli/compare.py
src/qibocal/cli/report.py
src/qibocal/cli/upload.py
src/qibocal/protocols/classification/classification.py
src/qibocal/protocols/tomographies/state_tomography.py

Apparently, UTF-8 has been accepted by Python as the default encoding, but it will only happen on py3.15
https://peps.python.org/pep-0686/
Currently, there is no reason why people may expect to be using anything differently on Linux and MacOS. But Windows users may experience some troubles in the meanwhile.
> Developers using macOS or Linux may forget that the default encoding is not always UTF-8.
> For example, using long_description = open("README.md").read() in setup.py is a common mistake. Many Windows users cannot install such packages if there is at least one non-ASCII character (e.g. emoji, author names, copyright symbols, and the like) in their UTF-8-encoded README.md file.
>
> Of the 4000 most downloaded packages from PyPI, 489 use non-ASCII characters in their README, and 82 …

Enforce utf-8 encoding on all write operations

---

README.md

I am not sure if I did something wrong, however while playing around with #1181 using the README example, I found that `platform.connect()` is needed before doing the acquisition. If that's actually true, we should correct the README.

Missing `platform.connect()` in README?

---

src/qibocal/protocols/two_qubit_interaction/chevron/chevron.py
src/qibocal/protocols/two_qubit_interaction/chevron/utils.py

The fitting procedure for the chevron protocol with an `iSWAP` was incorrect because we were just using the same procedure used for the `CZ`, while for the `iSWAP` the duration of the gate should be half the oscillation period.
I've also removed an additional X pulse for the chevron sequence that was added to improve the plot for the `CZ` case which is not necessary for the `iSWAP`.

Minor fixes for iSWAP chevron protocol

---

src/qibocal/protocols/resonator_spectroscopies/resonator_spectroscopy.py

When running at low power we were not updating the `dressed_resonator_frequency` which is what we are scanning around.

Fix update in resonator spectroscopy at low power
