qiboteam/qibocal

src/qcvv/cli/builders.py
Small changes to the platform runcard loading/saving to allow passing parameters from every routine to the next one. This should be useful for autocalibration.
When a qq job is launched, the `ActionBuilder` creates a copy (named new_platform.yml) of the current qibolab runcard to the qq folder and defines the platorm using this copy as a custom runcard. The new_platform.yml is updated after every routine using the results of fitting and reloaded in the next routine using `platform.reload_settings()`.This should allow to automatically pass the latest parameters to each calibration.
If one executes an action runcard containing all the required calibrations the final version of new_platform.yml will contain all the calibrated parameters.
=> Update platform runcard after every calibration

poetry.lock, pyproject.toml
Closes #98.
Some outdated dependencies were triggering some security vulnerabilities.
In this PR I've have updated the dependencies that were causing problems.
=> Fix security problems

doc/source/conf.py
=> Back to furo font

src/qibocal/calibrations/characterization/rabi.py, src/qibocal/cli/builders.py
In this PR all the Rabi routines are updated according to #189.
Checklist:
=> Refactor 1: Rabi

src/qibocal/calibrations/characterization/allXY.py, src/qibocal/calibrations/characterization/calibrate_qubit_states.py, src/qibocal/calibrations/characterization/flipping.py, src/qibocal/calibrations/characterization/qubit_spectroscopy.py, src/qibocal/calibrations/characterization/rabi.py, src/qibocal/calibrations/characterization/ramsey.py, src/qibocal/calibrations/characterization/resonator_spectroscopy.py, src/qibocal/calibrations/characterization/resonator_spectroscopy_sample.py, src/qibocal/cli/builders.py, src/qibocal/plots/allXY.py
Fixing a minor typo following PR #189.
The error is not triggered by single qubit platforms but only for multi qubit platforms.
Checklist:
=> Minor fix useful for multiplex

.github/workflows/tests.yml
This PR modify the workflows in order to use the ones stored in `qiboteam/workflows` (see qiboteam/workflows#23).
Checklist:
=> workflows migration 

src/qibocal/fitting/methods.py
This PR closes #225. It is not tested on hardware. There was a $2\pi$ factor missing.
Checklist:
=> Fix ramsey fit

src/qibocal/cli/_base.py
This PR fixes the issue reported by @maxhant in #212 . Please confirm that works in windows systemes as expected.
Checklist:
=> pathlib qq-compare

src/qibocal/calibrations/characterization/allXY.py, src/qibocal/cli/_base.py, src/qibocal/cli/builders.py, src/qibocal/web/report.py
=> Dump report after each routine

doc/source/api-reference/qibocal.rst, src/qibocal/calibrations/niGSC/XIdrb.py, src/qibocal/calibrations/niGSC/basics/plot.py, src/qibocal/calibrations/niGSC/basics/utils.py, src/qibocal/tests/test_niGSC_fitting.py, src/qibocal/tests/test_niGSC_simulfilteredrb.py, src/qibocal/tests/test_niGSC_standardrb.py, src/qibocal/tests/test_niGSC_xidrb.py
In this PR I'll try to tackle the third point in #249.
As I already mentioned there this PR is mainly to share the results of multiple runs of the workflows after attempting several fixes.
Checklist:
=> Attempting to fix tests before release

doc/source/api-reference/qibocal.rst, poetry.lock, pyproject.toml, src/qibocal/calibrations/niGSC/XIdrb.py, src/qibocal/calibrations/niGSC/basics/plot.py, src/qibocal/calibrations/niGSC/basics/utils.py, src/qibocal/tests/test_niGSC_experiment.py, src/qibocal/tests/test_niGSC_fitting.py, src/qibocal/tests/test_niGSC_simulfilteredrb.py, src/qibocal/tests/test_niGSC_standardrb.py, src/qibocal/tests/test_niGSC_xidrb.py
In this PR I update pint-pandas to the latest tag (0.3)
Checklist:
=> Upgrade pint-pandas

.github/workflows/deploy.yml, .github/workflows/tests.yml
This PR is related to qiboteam/workflows#36 and #249 (second point).
I'm not an expert in workflows so I'm open to suggestions (especially from @AleCandido :) ). 
Checklist:
=> Add workflow for poetry deployment

runcards/auto_spectroscopy.yml, src/qibocal/auto/execute.py, src/qibocal/cli/auto_builder.py, src/qibocal/protocols/characterization/__init__.py, src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/web/templates/autocalibration.html
=> deploy resonator punchout and minor fixes

runcards/autocalibration_qblox.yml, src/qibocal/protocols/characterization/classification.py
This PR implements the contour plot in the auto-calibration's classification routine.
Checklist:
=> Contour plot in classification

extras/classification/play.py, src/qibocal/fitting/classifier/qblox_fit.py, src/qibocal/fitting/classifier/run.py, tests/test_classifier.py
This PR benchmarks the Qblox classifier asked in #305.
Checklist:
=> Qblox classifier

src/qibocal/calibrations/niGSC/XIdrb.py, src/qibocal/calibrations/niGSC/basics/noisemodels.py, tests/test_niGSC_noisemodels.py, tests/test_niGSC_simulfilteredrb.py, tests/test_niGSC_standardrb.py
=> Fix NIGSC tests

poetry.lock, pyproject.toml
@scarrazza after merging this we should be able to make a new release for qibocal.
Checklist:
=> Update lock to match qibolab 0.0.3

src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/protocols/characterization/utils.py
Fixing a bug concerning the amplitude computed with `resonator_punchout`.
I want to take a look also the `resonator_punchout_attenuation`.
Checklist:
=> Fix punchout platform update

src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py, src/qibocal/protocols/characterization/classification.py, src/qibocal/protocols/characterization/coherence/spin_echo.py, src/qibocal/protocols/characterization/coherence/t1.py, src/qibocal/protocols/characterization/coherence/t2.py, src/qibocal/protocols/characterization/dispersive_shift.py, src/qibocal/protocols/characterization/flipping.py, src/qibocal/protocols/characterization/flux_depedence/qubit_flux_dependence.py, src/qibocal/protocols/characterization/flux_depedence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/qubit_spectroscopy.py, src/qibocal/protocols/characterization/rabi/amplitude.py, src/qibocal/protocols/characterization/rabi/length.py, src/qibocal/protocols/characterization/ramsey.py, src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/protocols/characterization/resonator_punchout_attenuation.py, src/qibocal/protocols/characterization/resonator_spectroscopy.py, src/qibocal/protocols/characterization/resonator_spectroscopy_attenuation.py
=> Introduce QubitID

.pre-commit-config.yaml, src/qibocal/auto/graph.py, src/qibocal/calibrations/__init__.py, src/qibocal/calibrations/characterization/calibrate_qubit_states.py, src/qibocal/cli/auto_builder.py, src/qibocal/plots/__init__.py, src/qibocal/web/server.py, tests/test_RB_fitting.py, tests/test_niGSC_circuitfactory.py, tests/test_niGSC_experiment.py, tests/test_niGSC_qq.py
=> Add pycln to pre-commit hooks

src/qibocal/protocols/characterization/flux_depedence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/rabi/amplitude.py, src/qibocal/protocols/characterization/rabi/length_sequences.py, src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
Some fixes related to the merge of #372.
Checklist:
=> General fixes

src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py, src/qibocal/protocols/characterization/resonator_punchout.py
Fix the missing axis name and a typo.
Checklist:
=> Rb plot fix

src/qibocal/protocols/characterization/allxy/allxy.py, src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
=> Change names AllXY plotting

.github/pull_request_template.md, runcards/README.md, runcards/actions_qq.yml
Closes #444.
This PR also updates the PR template following #445.
Let me know if you agree @Edoardo-Pedicillo.
Compatible branches:
- Qibolab: `main`
- Qibolab_platform_qrc: `main`
Checklist:
=> Update runcards folder and improve PR template

src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/utils.py, tests/runcards/protocols.yml
Implemented flux dependence routines fitting
Checklist:
=> adapting flux routines fitting to the latest version of qibocal

src/qibocal/protocols/characterization/__init__.py, src/qibocal/protocols/characterization/coherence/utils.py, src/qibocal/protocols/characterization/coherence/zeno.py, tests/runcards/protocols.yml
I didn't measure any increase of T1. As per https://link.aps.org/accepted/10.1103/PhysRevLett.118.240401:
The observed T1 of the qubit in the presence of these measurements does decrease, though we emphasize that this alteration of the decay rate is not a Zeno effect as it can easily be explained by considering the non-QND character of the measurement.
For now it can serve to test sequences with multiple readouts I suppose.
FIX: Code repetition on the utils.
It will only work when using https://github.com/qiboteam/qibolab/pull/517 and Zurich.
Checklist:
=> Zeno prototype

src/qibocal/fitting/classifier/qubit_fit.py, src/qibocal/protocols/characterization/classification.py
This PR fixes the threshold value computed by `Qubit Fit`.
The problem was the one already detected in #305.
I've also decided to show the ROC curve only when more than one classifier is used.
Checklist:
=> Fix classification after #447

src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/utils.py
=> Adjusting flux spectroscopy report

pyproject.toml, src/qibocal/protocols/characterization/__init__.py, src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py, src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power.py, tests/runcards/protocols.yml
=> Add twpa protocols after release

serverscripts/qibocal-index-reports.py, serverscripts/web/index.html, src/qibocal/cli/_base.py, src/qibocal/cli/upload.py
=> adding tag option in qq upload

src/qibocal/protocols/characterization/classification.py, src/qibocal/update.py, tests/test_update.py
=> Add fidelity to classification

src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py, src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power.py, src/qibocal/update.py, tests/test_update.py
=> Implement update for twpa optimization protocols

src/qibocal/protocols/characterization/__init__.py, src/qibocal/protocols/characterization/rabi/amplitude.py, src/qibocal/protocols/characterization/rabi/amplitude_msr.py, src/qibocal/protocols/characterization/rabi/ef.py, src/qibocal/protocols/characterization/rabi/length.py, src/qibocal/protocols/characterization/rabi/length_msr.py, src/qibocal/protocols/characterization/rabi/length_sequences.py, src/qibocal/protocols/characterization/rabi/utils.py, src/qibocal/protocols/characterization/utils.py, src/qibocal/update.py, tests/runcards/protocols.yml
=> Rabi with probabilities

pyproject.toml
Closes #603.
Let me know if it is a reasonable solution or if you want to discard it.
Checklist:
=> Added url strings for homepage and documentation

runcards/monitor.yml, src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
=> msr->signal in runcards

src/qibocal/protocols/characterization/flux_dependence/avoided_crossing.py
=> fix msr in avoided crossing

src/qibocal/fitting/classifier/qubit_fit.py, src/qibocal/protocols/characterization/classification.py, src/qibocal/protocols/characterization/readout_characterization.py, src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py, src/qibocal/protocols/characterization/utils.py
Closes #606.
@stavros11 perhaps we could consider adding a qubit effective temperature attribute to `Qubit` in qibolab?
Checklist:
=> Adding effective qubit temperature to some protocols

src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
Closes #641.
Thanks for spotting this @stavros11. There was a factor 1e9 wrong for the fitted point.
Now I've fixed it and I've also added the possibility to toggle the fitted point.
Let me know if this works for you.
Checklist:
=> Fixing punchout plots

src/qibocal/auto/operation.py, src/qibocal/auto/task.py, src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
Cleanup and improvements to data abstraction initially done in #582.
Checklist:
=> Improve data abstraction

src/qibocal/cli/acquisition.py, src/qibocal/cli/autocalibration.py, src/qibocal/cli/utils.py, src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py, src/qibocal/update.py, src/qibocal/utils.py, tests/runcards/protocols.yml, tests/test_update.py
This updates the mechanism to dump platforms modified by https://github.com/qiboteam/qibolab/pull/758
Checklist:
=> Updating mechanism to dump platforms

src/qibocal/protocols/characterization/classification.py, tests/runcards/protocols.yml
I needed something to test the unrolling https://github.com/qiboteam/qibolab/pull/685 for Zurich with only uncalibrated qubits.
Checklist:
=> Add singleshot unrolling

src/qibocal/auto/task.py, src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/utils.py
To avoid errors which stop the execution when running flux dependence experiments.
Checklist:
=> Adding `try-except` block in flux fits

tests/runcards/protocols.yml, tests/runcards/protocols_couplers.yml, tests/test_protocols.py
Closes #776. I can try to look for a smarter way to avoid duplicating. 
Checklist:
=> Tests with dummy_couplers

src/qibocal/cli/report.py, src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
Fixes issues observed recently http://login.qrccluster.com:9000/4AiRpTwFR9WmGlFThJWr3w== with CHSH protocol.
Checklist:
=> Fixing CHSH plot generation

src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
=> Fix table rendering for CZ

src/qibocal/update.py, tests/test_update.py
Closes #785  @sorewachigauyo
Checklist:
=> Fixing T1, T2 and T2 echo update mechanism

src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/utils.py
Closes #782.
The fundamental idea is to use a confidence interval. Two separated masks are applied (second one to try to clean outliers).
Checklist:
=> Improving binary masks for flux fitting protocols

runcards/benchmarks/routines_benchmarks.yml
=> Fix outdated runcard

src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py, src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py, src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py, src/qibocal/protocols/characterization/flux_dependence/utils.py, src/qibocal/protocols/characterization/resonator_punchout.py, src/qibocal/protocols/characterization/utils.py
This PR solves #784 for the punchout.
http://login.qrccluster.com:9000/BZAFtNVxTkCdCB4t89e9IQ==/
Checklist:
=> Punchout with confidence intervals

src/qibocal/protocols/characterization/allxy/allxy.py
This PR closes #544 
- http://login.qrccluster.com:9000/7dNOKZ1nRfyOor6QjPj5nw==/ (main)
- http://login.qrccluster.com:9000/Uq_jtPLiSNWvZ-QJbRNPYg==/ (pr)
Checklist:
=> Error bars in Allxy

src/qibocal/protocols/characterization/flipping.py, src/qibocal/protocols/characterization/flipping_signal.py
Similar approach already followed in other protocols.
http://login.qrccluster.com:9000/HWM0P_piSxy1gFm4Ce9RBg==/
The fit is still not perfect, as soon as we have #761 performances should improve even more.
Checklist:
=> Use fft to enhance flipping fit

src/qibocal/protocols/characterization/flipping.py, src/qibocal/protocols/characterization/flipping_signal.py, tests/runcards/protocols.yml
=> feat: detuning for flipping

src/qibocal/protocols/characterization/__init__.py, tests/runcards/protocols.yml
=> fix: Restore allxy_drag_tuning

src/qibocal/auto/execute.py, src/qibocal/auto/history.py, src/qibocal/auto/runcard.py, src/qibocal/auto/task.py, src/qibocal/cli/acquisition.py, src/qibocal/cli/autocalibration.py, src/qibocal/cli/report.py, src/qibocal/web/report.py, src/qibocal/web/templates/template.html, tests/test_protocols.py, tests/test_task_options.py
Closes #506.
The issue was quite old, if I misunderstood the task let me know @alecandido, currently I just tried to simplify a bit the report generation.
Checklist:
=> Simplifying plot generation

src/qibocal/protocols/characterization/__init__.py, src/qibocal/protocols/characterization/randomized_benchmarking/filtered_rb.py, src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py, src/qibocal/protocols/characterization/randomized_benchmarking/utils.py, tests/runcards/protocols.yml, tests/runcards/rb_noise_protocols.yml, tests/test_randomized_benchmarking.py
=> feature: implement filtered rb

src/qibocal/protocols/two_qubit_interaction/chsh/protocol.py
Fix a `KeyError` that was appearing from time to time when running CHSH on GitHub.
Checklist:
=> Correct bug in CHSH

src/qibocal/protocols/rabi/amplitude.py, src/qibocal/protocols/rabi/amplitude_frequency_signal.py, src/qibocal/protocols/rabi/amplitude_signal.py, src/qibocal/protocols/rabi/ef.py, src/qibocal/protocols/rabi/length.py, src/qibocal/protocols/rabi/length_frequency_signal.py, src/qibocal/protocols/rabi/length_signal.py, src/qibocal/update.py
=>  update both amplitude and duration in Rabi protocols

src/qibocal/cli/report.py, src/qibocal/protocols/coherence/spin_echo.py, src/qibocal/protocols/coherence/t1.py, src/qibocal/protocols/coherence/t2.py, src/qibocal/protocols/coherence/utils.py, src/qibocal/protocols/coherence/zeno.py, src/qibocal/protocols/coherence/zeno_signal.py, tests/test_crosstalk.py
Closes #881
There was a side effect generated by #740 with the attribute `pcov`.
Now everything should work as expected: http://login.qrccluster.com:9000/u9qq4XbsQ8iGMox6bTBayA==
Checklist:
=> Fixing T1 fit

src/qibocal/protocols/two_qubit_interaction/cz_virtualz.py
=> Adding coupler pulse to `cz_virtualz` protocols

README.md
This is a PR just because we can not edit main :P
=> Tiny README patch

src/qibocal/protocols/randomized_benchmarking/filtered_rb.py, src/qibocal/protocols/randomized_benchmarking/standard_rb.py, src/qibocal/protocols/randomized_benchmarking/utils.py
This is a rough patch for the problem found in https://github.com/qiboteam/qibolab_platforms_qrc/pull/151#issuecomment-2233114264
A better solution is postponed to a different version of Qibolab/Qibocal.
=> Set platform in RB backend

src/qibocal/auto/history.py, tests/test_protocols.py
=> Dump using `TaskId`

src/qibocal/protocols/classification.py, src/qibocal/protocols/rabi/length.py, src/qibocal/protocols/rabi/length_signal.py, src/qibocal/protocols/rabi/utils.py
=> Update for new qubits/channels

src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py
This is the reason why I was not getting good results with circuits.
I was able to calibrate one pair of  `qw11q` (I will upload the calibration shortly)
http://login.qrccluster.com:9000/lGY0gU66S-2hnVN3JtNCUA==/
Checklist:
=> Fix bug in virtual phase calculation for CZ gate

runcards/actions_qq.yml, src/qibocal/protocols/dispersive_shift.py
This PR updates the coupling after the execution of the dispersive shift.
http://login.qrccluster.com:9000/uAibm0TISF-mW_mtaUkRFQ==/ (not the best parameters, but it is just a test)
Checklist:
=> Update coupling in dispersive shift protocol

doc/source/protocols/chevron.rst
I tried to write a more complete documentation for the chevron routine.
=> Chevron doc

src/qibocal/protocols/classification.py
This PR adds SNR to the single shot classification protocol.
Here is an example: http://login.qrccluster.com:9000/ZvU2FqWsQBqJp0xldDkryA==/
=> Adding SNR to classification

src/qibocal/auto/transpile.py, tests/test_transpile.py
Some changes where necessary to port #1077 to 0.2, I've started to implemented them in #990  but I thought that it might be better to have a separate PR.
I've also added a test to make sure that our implementation works as expected.
=> Propagate #1077 to 0.2

src/qibocal/auto/history.py
=> Fix history protocols order

src/qibocal/protocols/ramsey/ramsey.py, src/qibocal/protocols/ramsey/ramsey_zz.py
In this PR I'm adding the computation of the qubit-qubit coupling in the ZZ protocol.
I've followed this [reference](https://global.oup.com/academic/product/quantum-information-science-9780198787488?cc=it&lang=en&).
This PR should also close https://github.com/qiboteam/qibocal/issues/863.
=> Adding qubit-qubit coupling to ZZ protocol

src/qibocal/protocols/drag_simple.py
Closes #1122.
The problem was related to a wrong range in the plot.
I've also improved the performance of the fit by providing a resonable initial guess.
Here is the updated plot:
=> Fixing drag simple plot

platforms/qubit/parameters.json
=> Correct parameters in `qubit` platform

doc/source/protocols/chevron.rst, doc/source/protocols/flipping.rst, doc/source/protocols/rabi/rabi.rst
Fix: small fixes for docs display
=> fix: fix issues in doc display

src/qibocal/protocols/readout/readout_mitigation_matrix.py
=> Fix readout mitigation protocol label

poetry.lock, pyproject.toml, src/qibocal/protocols/signal_experiments/time_of_flight_readout.py, tests/platforms/mock/parameters.json
This PR restore the compatibility with Qibolab main after merging https://github.com/qiboteam/qibolab/pull/1206
=> Set correct GaussianSquare parameters in mock platform

platforms/qubit/parameters.json, platforms/qutrit/parameters.json
=> Propagate `GaussianSquare` refactor to emulator platforms

poetry.lock, pyproject.toml
Update qibolab dep to the new version so that it is published by pypi.
=> update qibolab dep

src/qibocal/protocols/utils.py
We should now get values similar to what Hany was suggesting.
=> Fix 2 pi factor in qubit effective temperature

src/qibocal/protocols/drag/drag_simple.py
=> Fix readout pulses for `drag_simple` with unrolling 
